### ISSUE TITLE
Using Ctrl+Z on a shared board sometimes erases a very big part of the board

### ISSUE THREAD

**Issue by philardine** [tableaunoir/tableaunoir#113] opened 2021-01-22 17:47 UTC
Dear François,

Just for information...
I'm sorry I couldn't precisely determine the circumstances causing this annoying situation, so I can't yet describe how to reproduce it.
In particular, I don't know if the participants were doing silly things or not (but they had no privileges)...
And of course it was impossible (for me) to restore the state of the board before Ctrl+Z :'-(

I learned to use 'e' rather than 'Ctrl+Z' ;-)

**Comment by francoisschwarzentruber** [comment] 2021-01-23 20:24
Dear philardine,
I am sorry for this bug and I do not know the exact reason.
I improved (or think that I improved) a bit the architecture around Undo/redo, sharing and saving. But, I discover sth embarrassing: the server is very slow with long messages... (especially those for loading a board...). I have to understand the reason.
Thank your message. I will let you know.
Have a nice evening.

**Comment by philardine** [comment] 2021-01-24 19:03
Thank you for your efforts!
In the meantime I carefully use 'e' as a workaround ;-)

**Comment by francoisschwarzentruber** [comment] 2021-01-24 20:33
Most of the time, Ctrl + Z works perfectly. However I was able to reproduce the bug once, but the circumstances of the bug are very unclear. I added a condition (I identified the part that is responsible of the bug) and a message referring to this issue #113 (I do not know if that is a good idea of not). That is related to the new way of handling undo/redo, but the new way is much more easy and will probably solve the multi-user undo/redo issue #46!

Concerning the server, there are sometimes too many people that are connecting tableaunoir.irisa.fr, making the server shutdown. To cope with that, soon, the server will have more RAM and a better CPU, but I do not know when yet.

I hope we will find a solution quickly!

Thanks and good night!

**Comment by tekhnee** [comment] 2021-01-24 21:48
Dear @francoisschwarzentruber speaking of system capacities, may I ask what is the approximate number of users beyond which the performance of tableaunoir begins to degrade? Obviously this number is a function of server capacity, and perhaps amount of tableau content. But any relevant information you might be able to provide would be very much appreciated, as I don't have the resources to stress-test the system myself. Thank you for this extraordinary work!

**Comment by francoisschwarzentruber** [comment] 2021-01-25 07:15
Thank you for your message. Just to be clear, sorry, the Ctrl+Z bug is not due to the server. Sorry for having discussed that here. The current server tableaunoir.irisa.fr has 1Go of RAM and a small CPU (I have to ask to the IT team). There are 2000 persons per week, that is not lot but I expect that some connections are made at the same time so the server slows down.

**Comment by francoisschwarzentruber** [comment] 2021-01-25 19:34
There is an ugly patch now. If it works, then if the bug occurs
- the system will show "issue #113"
- the system tries to "repair" the undo/redo queue, maybe we should continue working.

**Comment by philardine** [comment] 2021-01-26 08:34
Dear François,

Thank you, I will try this as soon as possible.

Just a remark: when the Ctrl+Z bug arose we were about 35 users on a shared board with **privileged** access. I think that's still reasonable, isn't it?

**Comment by francoisschwarzentruber** [comment] 2021-01-26 16:51
Dear philardine,

oh, I have never used tableaunoir with 35 users! I am happy it somehow works. I experienced the bug, and a colleague of mine two, in sessions with two users. So the bug is unrelated to the number of users.

**Comment by francoisschwarzentruber** [comment] 2021-01-28 08:21
Dear philardine,
I experienced the issue #113 yesterday! However, with the ugly code that "repairs" the action stack (*), I was still able to undo, redo and save normally. So issue #113 is still there, but I guess is not as harmful as it was.

(*) the action stack may contain some "undefined" objects instead of concrete objets of class Action :(. And when I prove formally in my "head", undefined objects are never added! So I still do not understand the issue #113. The ugly reparation simply consists in removing all the undefined from the stack.

**Comment by philardine** [comment] 2021-01-28 15:51
Good news!

Btw I used tableaunoir this afternoon, but not enough during the session to be able to make any feedback: in particular, I did not need Ctrl+Z :'-(
Maybe I will be more lucky tomorrow?

**Comment by francoisschwarzentruber** [comment] 2021-01-28 19:06
Happy that your session went well. Aïe we are now all afraid of Ctrl+Z. Hope it will be solved soon. Good luck for your course tomorrow!

**Comment by francoisschwarzentruber** [comment] 2021-02-10 16:51
Dear Philardine,

I still have this bug, but it is not harmful. Sometimes, the message "issue #113" appears, but it does not cause any trouble. And you?
Btw, I hope you are fine.

**Comment by philardine** [comment] 2021-02-10 17:28
Dear François,

I still have this bug too, and you're wright, it's not harmful.
Once it happened to me to lose the name of all the participants after an « issue #113 » (don't know precisely when)... but I am not sure it was related to it.

I am fine but quite busy, and I hope you are fine too.
Thank you for this kind attention.

**Comment by francoisschwarzentruber** [comment] 2021-02-25 09:08
I improved a bit the code. The problem is that I can not figure out when issue #113 is occurring so... even if it is solved, I will not know it.

**Comment by francoisschwarzentruber** [comment] 2021-05-03 19:46
Dear philardine, do you still experience bug #113?

**Comment by philardine** [comment] 2021-05-06 07:14
Dear François,
Sorry for my late answer, I wasn't near my keyboard until now.
It has been a few days since I used tableaunoir (around april, the 8th and 9th). The context was: several students, giving their names, and only some of them where allowed to write.
I observed this error probably twice, resulting in all usernames disappearing. Aside from that, the app held up well and I was able to continue my teachings.
Cheers.

**Comment by francoisschwarzentruber** [comment] 2021-06-26 13:30
Dear Philardine,
I hope you are fine. Just to inform you, the mechanism of undo/redo has completely changed: now each user has its own undo/redo stack, which is different of the timeline. This bug can still occur but different reasons, more related to the animation editor.

**Comment by philardine** [comment] 2021-06-26 13:56
Hi François!
I'm fine thank you, and hope you are too :-) I'm so relieved this very special year is over ^^'
Thank you for your message. I hope you will have some fun and take little rest in summer...
Cheers and read you soon

**Comment by francoisschwarzentruber** [comment] 2022-09-20 20:04
Hello, I am wondering whether this problem still occurs. On my side, I never experienced this error again. And you?

**Comment by philardine** [comment] 2022-09-29 05:58
Hi François!
Nice to read about you :-) I hope you're fine.
I must admit that I haven't used tableaunoir much for a while :-/ which explanes why I am answering so late!
Well I have nothing more to say than in my previous comment of May '21... Maybe this thread should be closed?
Cheers and take care of you :-)

**Comment by francoisschwarzentruber** [comment] 2022-09-29 07:47
Thank you for your message. Hope you are fine too!
OK, I close this issue, and we reopen it if the problem again appears.
Have a nice day! :)

**Closed by francoisschwarzentruber** 2022-09-29 07:47 UTC
Labels: bug
